### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by vikramhanda0007** [tjoskar/react-lazyload-img#32]
./node_modules/@tjoskar/react-lazyload-img/dist/index.js:3
when  i am create a build then this issues appear. Please solve this issues asap

**Comment by tjoskar** [comment]
Hi,
How do you minify the code? What tool are you using? What does the error message say?

**Comment by tjoskar** [comment]
@vikramhanda0007, I have now published both commonJS and es2015-module. It may solve your problem.
